LOSJV-48 & EMP-825
Guaranteed-Rate/GuaranteedRate.Sextant pull request #136
Opened 2021-06-14 17:11 UTC by HarryCordewener

LOSKV-48: Add basic orgId config switching.
EMP-825: Change logging format.
Fix Integration Tests.

2021-06-14 17:12 UTC, HarryCordewener commented on GuaranteedRate.Sextant/Logging/SeriLogger.cs
> +                            formatter: new JsonFormatter(renderMessage: false),
EMP-825 is just this single change.

2021-06-14 18:26 UTC, TylerBrinkley commented on GuaranteedRate.Sextant/Config/IEncompassConfig.cs
> +        bool GetValue(string key, bool defaultValue, string orgId = null);
Since the original methods remain, I assume for binary compatibility, there seems to be no reason for these to have the orgId be declared as an optional argument.

2021-06-14 18:27 UTC, TylerBrinkley commented on GuaranteedRate.Sextant/Config/IEncompassConfig.cs
>          IEncompassConfig GetConfigGroup(string key);
Does this need an orgId equivalent?

2021-06-14 18:57 UTC, HarryCordewener commented on GuaranteedRate.Sextant/Config/IEncompassConfig.cs
>          IEncompassConfig GetConfigGroup(string key);
Creating an orgId equivalent of this would be difficult, as this kind of ignores the orgId format to begin with. But I am also fairly confident it doesn't get used at all.

2021-06-14 18:59 UTC, HarryCordewener commented on GuaranteedRate.Sextant/Config/IEncompassConfig.cs
> +        bool GetValue(string key, bool defaultValue, string orgId = null);
It's there to both keep the pattern that exists, as well as avoiding function-pattern duplicates. 
After all, it's hard to tell the difference between: `fn(string, string?, string?)` and `fn(string, string?)`
This exists in order to make changes as minimally invasive.

2021-06-14 19:00 UTC, HarryCordewener commented on GuaranteedRate.Sextant/Config/IEncompassConfig.cs
> +        bool GetValue(string key, bool defaultValue, string orgId = null);
Ah, I get what you are saying. 
`fn(string, string, string)` would be valid too.

2021-06-14 19:33 UTC, TylerBrinkley commented on GuaranteedRate.Sextant/Config/IEncompassConfig.cs
>          IEncompassConfig GetConfigGroup(string key);
Sounds good to me.

2021-06-14 20:23 UTC, HarryCordewener commented on GuaranteedRate.Sextant/Config/IEncompassConfig.cs
> +        bool GetValue(string key, bool defaultValue, string orgId = null);
With this change, for some reason it's suddenly failing to run the tests.

2021-06-15 20:59 UTC, HarryCordewener commented on GuaranteedRate.Sextant/Config/IEncompassConfig.cs
> +        bool GetValue(string key, bool defaultValue, string orgId = null);
Fixed

2021-06-15 21:02 UTC, TylerBrinkley approved these changes

2021-06-16 20:10 UTC, omedinaGR approved these changes

2021-06-16 21:26 UTC, GeorgeGomez requested changes

2021-06-16 21:26 UTC, GeorgeGomez commented on GuaranteedRate.Sextant.Integration.Core/IntegrationEncompassConfig.cs
> +        private string Keyname(string key, string orgId = null) => $"{orgId ?? _orgId}{((orgId ?? _orgId) == null ? "" : ".")}{key}";
I don't understand what is going on here. Could we simplify it a bit or add comments?

2021-06-16 21:26 UTC, GeorgeGomez commented on GuaranteedRate.Sextant.Integration.Core/IntegrationEncompassConfig.cs
> +        public ICollection<string> GetKeys() => throw new NotImplementedException();
Should all of these NotImplementedException functions be removed?

2021-06-16 21:26 UTC, GeorgeGomez commented on GuaranteedRate.Sextant.Integration.Core/IntegrationEncompassConfig.cs
> +            var value = ConfigurationManager.AppSettings[Keyname(key, orgId)] ?? ConfigurationManager.AppSettings[key];
what is happening here other than return the left side if not null etc. ? :)

2021-06-16 21:26 UTC, GeorgeGomez commented
Consider adding a bit more comments, thanks!

2021-06-17 13:25 UTC, TylerBrinkley commented on GuaranteedRate.Sextant.Integration.Core/IntegrationEncompassConfig.cs
> +        public ICollection<string> GetKeys() => throw new NotImplementedException();
I believe those are to implement all of `IEncompassConfig`.

2021-06-17 13:31 UTC, TylerBrinkley commented on GuaranteedRate.Sextant.Integration.Core/IntegrationEncompassConfig.cs
> +        private string Keyname(string key, string orgId = null) => $"{orgId ?? _orgId}{((orgId ?? _orgId) == null ? "" : ".")}{key}";
I agree it could be made a bit simpler by making it multiple lines like so.

```c#
private string Keyname(string key, string orgId = null)
{
    var prefix = orgId ?? _orgId;
    return $"{prefix}{(prefix == null ? "" : ".")}{key}";
}
```

2021-06-17 15:26 UTC, HarryCordewener commented on GuaranteedRate.Sextant.Integration.Core/IntegrationEncompassConfig.cs
> +            var value = ConfigurationManager.AppSettings[Keyname(key, orgId)] ?? ConfigurationManager.AppSettings[key];
That's all it's doing. It tries to get the orgId specific config file. And if it can't find it, gets the default.

2021-06-17 15:27 UTC, HarryCordewener commented on GuaranteedRate.Sextant.Integration.Core/IntegrationEncompassConfig.cs
> +        private string Keyname(string key, string orgId = null) => $"{orgId ?? _orgId}{((orgId ?? _orgId) == null ? "" : ".")}{key}";
^ Would this be easier for you to read? @GeorgeGomez

2021-06-17 16:31 UTC, GeorgeGomez commented on GuaranteedRate.Sextant.Integration.Core/IntegrationEncompassConfig.cs
> +        private string Keyname(string key, string orgId = null) => $"{orgId ?? _orgId}{((orgId ?? _orgId) == null ? "" : ".")}{key}";
yeah, I will take that and a comment explaining what prefix means related to orgId and multi tenancy. thank you.

2021-06-17 16:32 UTC, GeorgeGomez approved these changes
consider sprinkling a comment or two. thanks!

2021-06-17 17:57 UTC, HarryCordewener commented on GuaranteedRate.Sextant.Integration.Core/IntegrationEncompassConfig.cs
> +        private string Keyname(string key, string orgId = null) => $"{orgId ?? _orgId}{((orgId ?? _orgId) == null ? "" : ".")}{key}";
The prefix is explained at the top of the interface.

2021-06-17 18:01 UTC, GeorgeGomez commented on GuaranteedRate.Sextant.Integration.Core/IntegrationEncompassConfig.cs
> +        private string Keyname(string key, string orgId = null) => $"{orgId ?? _orgId}{((orgId ?? _orgId) == null ? "" : ".")}{key}";
@HarryCordewener where?

2021-06-17 19:27 UTC, GeorgeGomez approved these changes

2021-06-17 20:40 UTC, TylerBrinkley commented on GuaranteedRate.Sextant/Config/JsonEncompassConfig.cs
> +        [MethodImpl(MethodImplOptions.AggressiveInlining)]
AgressiveInlining? That seems a bit extreme for config reading don't you think?

2021-06-17 20:48 UTC, HarryCordewener commented on GuaranteedRate.Sextant/Config/JsonEncompassConfig.cs
> +        [MethodImpl(MethodImplOptions.AggressiveInlining)]
It's not that extreme for a simple helper private function. And since we do quite a bit of config reading, I don't think it's unwarranted.

2021-06-17 22:03 UTC, GeorgeGomez commented on GuaranteedRate.Sextant/Config/JsonEncompassConfig.cs
> +        [MethodImpl(MethodImplOptions.AggressiveInlining)]
I don't think we need that. It is a config file, not a game loop :)  Trust the compiler. What are the performance gains?

2021-06-22 18:55 UTC, merged